[package]
name = "sabita-app"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4"
diesel = { version = "2.2.0", features = ["chrono", "returning_clauses_for_sqlite_3_35", "sqlite"] }
diesel-async = { version = "0.7.0", features = ["sqlite"] }
diesel-derive-enum = { version = "3.0.0-beta.1", features = ["sqlite"] }
iced = { version = "0.14.0", features = ["svg"] }
iced_anim = "0.3.1"
iced_font_awesome = "0.4.4"
iced_test = "0.14.0"
kavita-client = { path = "../kavita-client" }
reqwest = "0.13"
rfd = { version = "0.17.2", features = ["xdg-portal"] }
tokio = { version = "1", features = ["rt", "sync"] }
uuid = { version = "1", features = ["v4"] }
